/*
 * This source file was generated by the Gradle 'init' task
 */
package basic_hash;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.io.*;
import java.util.Scanner;

class UITest {
  private ByteArrayOutputStream outputStream;
  private PrintStream originalOut;
  private InputStream originalIn;
  private UI SUT;

  /**
   * Setup the system under test before each test.
   */
  @BeforeEach
  void setUp() {
    // Redirect System.out to capture console output
    outputStream = new ByteArrayOutputStream();
    originalOut = System.out;
    System.setOut(new PrintStream(outputStream));

    // Backup System.in to restore later
    originalIn = System.in;

    // Provide mock input for any methods that may need it
    InputStream mockIn = new ByteArrayInputStream("".getBytes()); // No actual input is needed
    System.setIn(mockIn);

    // Initialize the system under test (UI)
    SUT = new UI(new Scanner(System.in, "UTF-8"));
  }

  /**
   * Reset the console between the tests.
   */
  @AfterEach
  void tearDown() {
      // Restore original System.out and System.in
      System.setOut(originalOut);
      System.setIn(originalIn);
  }

  /**
   * Test that the UI can show messages.
   */
  @Test void UICanShowMessage() {
    String message = "test message";
    SUT.showMessage(message);

    String consoleOutput = outputStream.toString().trim();

    assertTrue(consoleOutput.contains(message));
  }
}
